global:
  batch_size: 1
  sleep: 1s
  datasource:
    transaction_isolation: REPEATABLE READ
    src:
      addr: 127.0.0.1:3306
      user: root
      pass: "1234"
      dbname: ccc
    dst:
      addr: 10.1.154.36:3306
      user: root
      pass: "1234"
      dbname: ccc_archive
rules:
  - table: Orders
    where: 1=1
    pk: Id
    batch_size: 5
    deps:
      - table: OrderDetails
        pk: DetailId
        key: OrderId